"""rename content to text

Revision ID: 643e83a96e73
Revises: fac3bc6c6736
Create Date: 2025-12-07 08:04:55.857711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643e83a96e73'
down_revision: Union[str, Sequence[str], None] = 'fac3bc6c6736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription_blocks', sa.Column('text', sa.Text(), nullable=True))
    op.drop_column('transcription_blocks', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription_blocks', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('transcription_blocks', 'text')
    # ### end Alembic commands ###
