"""add_settings_tables

Revision ID: 68a35a983a29
Revises: 643e83a96e73
Create Date: 2025-12-07 14:50:34.719648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a35a983a29'
down_revision: Union[str, Sequence[str], None] = '643e83a96e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_id'), 'prompt_templates', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_templates_title'), 'prompt_templates', ['title'], unique=False)
    op.create_table('vocabulary_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reading', sa.String(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_items_id'), 'vocabulary_items', ['id'], unique=False)
    op.create_index(op.f('ix_vocabulary_items_reading'), 'vocabulary_items', ['reading'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocabulary_items_reading'), table_name='vocabulary_items')
    op.drop_index(op.f('ix_vocabulary_items_id'), table_name='vocabulary_items')
    op.drop_table('vocabulary_items')
    op.drop_index(op.f('ix_prompt_templates_title'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_id'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
