"""Add missing columns for sessions and blocks

Revision ID: 6e679058b064
Revises: c7d2e601bc17
Create Date: 2025-12-15 06:07:51.948629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e679058b064'
down_revision: Union[str, Sequence[str], None] = 'c7d2e601bc17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('sessions', sa.Column('color', sa.String(), nullable=True))
    op.add_column('transcription_blocks', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('transcription_blocks', sa.Column('color', sa.String(), nullable=True))
    op.add_column('transcription_blocks', sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcription_blocks', 'order_index')
    op.drop_column('transcription_blocks', 'color')
    op.drop_column('transcription_blocks', 'is_deleted')
    op.drop_column('sessions', 'color')
    op.drop_column('sessions', 'is_deleted')
    # ### end Alembic commands ###
