"""Add editor revisions table

Revision ID: c7d2e601bc17
Revises: 68a35a983a29
Create Date: 2025-12-07 16:16:12.551197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d2e601bc17'
down_revision: Union[str, Sequence[str], None] = '68a35a983a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editor_revisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editor_revisions_id'), 'editor_revisions', ['id'], unique=False)
    op.create_index(op.f('ix_editor_revisions_session_id'), 'editor_revisions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_editor_revisions_session_id'), table_name='editor_revisions')
    op.drop_index(op.f('ix_editor_revisions_id'), table_name='editor_revisions')
    op.drop_table('editor_revisions')
    # ### end Alembic commands ###
